#+BEGIN_COMMENT
.. title: Reading data with non-native encoding in R
.. slug: reading-data-with-non-native-encoding-in-r
.. date: 2016-06-14 13:57:09 UTC-04:00
.. tags: R,Encoding,Files,UTF-8,SHIFT-JIS
.. category: R
.. link: 
.. description: 
.. type: text
#+END_COMMENT



#+PROPERTY: cache no
#+PROPERTY: results output
#+PROPERTY: session *R*
#+PROPERTY: exports both

* Best practices for importing files with non-native encoding in R

This section gives the basic facts and recommendations for importing files with arbitrary encoding. If you are on a deadline and just need to get the job done this section should be all you need. Additional background and discussion is presented in later sections.

To read a text file with non ASCII encoding into R you should a) determine the encoding and b) read it in such a way that the information is re-encoded into UTF-8, and c) ignore the bug in the ~data.frame~ print method on Windows. Hopefully the encoding is specified in the documentation that accompanied your data. If not, you can guess the encoding using the ~stri_read_raw~ and ~stri_enc_detect~ functions in the =`stringi`= package. You can ensure that the information is re-encoded to UTF-8 by using the =`readr`= package.

For example, I have two versions of a file containing numbers and Japanese characters: =japanese_utf8.csv= is encoded in UTF-8, and =japanese_shiftjis.csv= is encoded in SHIFT-JIS. We can read these files as follows on any platform (Windows, Linux, Mac):

#+BEGIN_SRC R
  library(readr)
  read_csv("example_files/japanese_utf8.csv",
           locale = locale(encoding = "UTF-8"))
  read_csv("example_files/japanese_shiftjis.csv",
           locale = locale(encoding = "SHIFT-JIS"))
#+END_SRC

#+RESULTS:
#+begin_example

Attaching package: ‘readr’

The following object is masked from ‘package:rvest’:

    guess_encoding
    No.         発行日 朝夕刊         面名 ページ    文字数
1 00001 2015年09月25日   週刊     週刊朝日    022 05786文字
2 00002 2015年09月25日   週刊     週刊朝日    018 05422文字
3 00003 2015年09月21日   朝刊       ３総合    003 01066文字
4 00004 2015年09月21日   朝刊 オピニオン２    008 00449文字
5 00005 2015年09月21日   朝刊       ３総合    003 02222文字
6 00006 2015年09月21日   朝刊       ２総合    002 02326文字
    No.         発行日 朝夕刊         面名 ページ    文字数
1 00001 2015年09月25日   週刊     週刊朝日    022 05786文字
2 00002 2015年09月25日   週刊     週刊朝日    018 05422文字
3 00003 2015年09月21日   朝刊       ３総合    003 01066文字
4 00004 2015年09月21日   朝刊 オピニオン２    008 00449文字
5 00005 2015年09月21日   朝刊       ３総合    003 02222文字
6 00006 2015年09月21日   朝刊       ２総合    002 02326文字
#+end_example

On Windows there is a bug in ~print.data.frame~ that causes ~data.frame~'s with UTF-8 encoded columns to be displayed incorrectly in non UTF-8 locales. Running the above example on Windows produces this:

#+begin_example
    No.         <U+767A><U+884C><U+65E5> <U+671D><U+5915><U+520A>                          <U+9762><U+540D> <U+30DA><U+30FC><U+30B8> <U+6587><U+5B57><U+6570>
1 00001 2015<U+5E74>09<U+6708>25<U+65E5>         <U+9031><U+520A>          <U+9031><U+520A><U+671D><U+65E5>                      022    05786<U+6587><U+5B57>
2 00002 2015<U+5E74>09<U+6708>25<U+65E5>         <U+9031><U+520A>          <U+9031><U+520A><U+671D><U+65E5>                      018    05422<U+6587><U+5B57>
3 00003 2015<U+5E74>09<U+6708>21<U+65E5>         <U+671D><U+520A>                         3<U+7DCF><U+5408>                      003    01066<U+6587><U+5B57>
4 00004 2015<U+5E74>09<U+6708>21<U+65E5>         <U+671D><U+520A> <U+30AA><U+30D4><U+30CB><U+30AA><U+30F3>2                      008    00449<U+6587><U+5B57>
5 00005 2015<U+5E74>09<U+6708>21<U+65E5>         <U+671D><U+520A>                         3<U+7DCF><U+5408>                      003    02222<U+6587><U+5B57>
6 00006 2015<U+5E74>09<U+6708>21<U+65E5>         <U+671D><U+520A>                         2<U+7DCF><U+5408>                      002    02326<U+6587><U+5B57>
> read_csv("example_files/japanese_shiftjis.csv",
+          locale = locale(encoding = "SHIFT-JIS"))
    No.         <U+767A><U+884C><U+65E5> <U+671D><U+5915><U+520A>                          <U+9762><U+540D> <U+30DA><U+30FC><U+30B8> <U+6587><U+5B57><U+6570>
1 00001 2015<U+5E74>09<U+6708>25<U+65E5>         <U+9031><U+520A>          <U+9031><U+520A><U+671D><U+65E5>                      022    05786<U+6587><U+5B57>
2 00002 2015<U+5E74>09<U+6708>25<U+65E5>         <U+9031><U+520A>          <U+9031><U+520A><U+671D><U+65E5>                      018    05422<U+6587><U+5B57>
3 00003 2015<U+5E74>09<U+6708>21<U+65E5>         <U+671D><U+520A>                         3<U+7DCF><U+5408>                      003    01066<U+6587><U+5B57>
4 00004 2015<U+5E74>09<U+6708>21<U+65E5>         <U+671D><U+520A> <U+30AA><U+30D4><U+30CB><U+30AA><U+30F3>2                      008    00449<U+6587><U+5B57>
5 00005 2015<U+5E74>09<U+6708>21<U+65E5>         <U+671D><U+520A>                         3<U+7DCF><U+5408>                      003    02222<U+6587><U+5B57>
6 00006 2015<U+5E74>09<U+6708>21<U+65E5>         <U+671D><U+520A>                         2<U+7DCF><U+5408>                      002    02326<U+6587><U+5B57>

#+end_example
which looks terrible but does not actually indicate a problem. The information is encoded correctly, but due to a long-standing bug it is _displayed_ incorrectly. You can check to see if the values are correct by converting the data.frame by (ab)using ~print.listof~, e.g.,

#+BEGIN_SRC R :eval no
  print.listof(read_csv("example_files/japanese_utf8.csv",
                        locale = locale(encoding = "UTF-8")))
  print.listof(read_csv("example_files/japanese_shiftjis.csv",
+          locale = locale(encoding = "SHIFT-JIS")))
#+END_SRC

#+begin_example
No. :
[1] "00001" "00002" "00003" "00004" "00005" "00006"

発行日 :
[1] "2015年09月25日" "2015年09月25日" "2015年09月21日" "2015年09月21日" "2015年09月21日" "2015年09月21日"

朝夕刊 :
[1] "週刊" "週刊" "朝刊" "朝刊" "朝刊" "朝刊"

面名 :
[1] "週刊朝日"     "週刊朝日"     "３総合"       "オピニオン２" "３総合"       "２総合"      

ページ :
[1] "022" "018" "003" "008" "003" "002"

文字数 :
[1] "05786文字" "05422文字" "01066文字" "00449文字" "02222文字" "02326文字"


No. :
[1] "00001" "00002" "00003" "00004" "00005" "00006"

発行日 :
[1] "2015年09月25日" "2015年09月25日" "2015年09月21日" "2015年09月21日" "2015年09月21日" "2015年09月21日"

朝夕刊 :
[1] "週刊" "週刊" "朝刊" "朝刊" "朝刊" "朝刊"

面名 :
[1] "週刊朝日"     "週刊朝日"     "３総合"       "オピニオン２" "３総合"       "２総合"      

ページ :
[1] "022" "018" "003" "008" "003" "002"

文字数 :
[1] "05786文字" "05422文字" "01066文字" "00449文字" "02222文字" "02326文字"
#+end_example

To recap: regardless of platform (Windows, Mac Linux), use the =`readr`= package to read data into R. This will re-encode the contents of the file to UTF-8 for you. Make sure you specify the encoding using the ~locale~ argument as shown in the example above. Ignore the ugly =print.data.frame= bug and use =print.listof= to check that your data was imported correctly.

Those wishing for more details about this issue can read on.

* There are more encodings on this earth than dreamed of in your philosophy

I've been using R since 2006 or so, about a decade at the time of this writing. For the first two or three of those years I mostly ran OS X, and since then I've been running Linux. I have only occasionally run in to encoding problems when running R on those platforms, and any issues I did encounter were quickly resolved. Quite simply, text in R is not an issue on Mac and Linux.

Sadly, the R text encoding story on Windows is quite different. Since 2013 I've worked as a data analyst and consultant at Harvard University. In that capacity I've seen many students and researchers struggle with this issue, and the answers haven't always been clear to me, even after a decade of using R on a daily basis.

* What is the problem?

The problem is that the basic R functions for reading and writing data from and to files does no work in any reasonable way on Windows. Let's try it, using some simplified data from a project I worked on last year. For illustration I've created two files containing a mix of English letters, numbers, and Japanese characters. I saved one version with UTF-8 encoding, and another with SHIFT-JIS. On Linux we can read both files easily, provided only that we correctly specify the encoding if the file is not already encoded in UTF-8:

#+BEGIN_SRC R
  read.csv("example_files/japanese_utf8.csv")
#+END_SRC

#+RESULTS:
:   No.         発行日 朝夕刊         面名 ページ    文字数
: 1   1 2015年09月25日   週刊     週刊朝日     22 05786文字
: 2   2 2015年09月25日   週刊     週刊朝日     18 05422文字
: 3   3 2015年09月21日   朝刊       ３総合      3 01066文字
: 4   4 2015年09月21日   朝刊 オピニオン２      8 00449文字
: 5   5 2015年09月21日   朝刊       ３総合      3 02222文字
: 6   6 2015年09月21日   朝刊       ２総合      2 02326文字

#+BEGIN_SRC R
  read.csv("example_files/japanese_shiftjis.csv", fileEncoding = "SHIFT-JIS")
#+END_SRC

#+RESULTS:
:   No.         発行日 朝夕刊         面名 ページ    文字数
: 1   1 2015年09月25日   週刊     週刊朝日     22 05786文字
: 2   2 2015年09月25日   週刊     週刊朝日     18 05422文字
: 3   3 2015年09月21日   朝刊       ３総合      3 01066文字
: 4   4 2015年09月21日   朝刊 オピニオン２      8 00449文字
: 5   5 2015年09月21日   朝刊       ３総合      3 02222文字
: 6   6 2015年09月21日   朝刊       ２総合      2 02326文字

On Windows things are much more difficult:

#+BEGIN_SRC R :eval no
  read.csv("example_files/japanese_utf8.csv")
#+END_SRC

#+RESULTS:
:  No.         ç.ºè.Œæ.. æœ.å..å.Š             é..å.. ãƒšãƒ.ã..   æ..å..æ..
: 1   1 2015å¹´09æœˆ25æ—¥    é€±åˆŠ       é€±åˆŠæœæ—¥        22 05786æ–‡å­—
: 2   2 2015å¹´09æœˆ25æ—¥    é€±åˆŠ       é€±åˆŠæœæ—¥        18 05422æ–‡å­—
: 3   3 2015å¹´09æœˆ21æ—¥    æœåˆŠ          ï¼“ç·åˆ         3 01066æ–‡å­—
: 4   4 2015å¹´09æœˆ21æ—¥    æœåˆŠ ã‚ªãƒ”ãƒ‹ã‚ªãƒ³ï¼’         8 00449æ–‡å­—
: 5   5 2015å¹´09æœˆ21æ—¥    æœåˆŠ          ï¼“ç·åˆ         3 02222æ–‡å­—
: 6   6 2015å¹´09æœˆ21æ—¥    æœåˆŠ          ï¼’ç·åˆ         2 02326æ–‡å­—


#+BEGIN_SRC R :eal no
  read.csv("example_files/japanese_utf8.csv", fileEncoding = "UTF-8")
#+END_SRC

#+RESULTS:
: read.csv("example_files/japanese_utf8.csv", fileEncoding = "UTF-8")
: [1] No. X  
: <0 rows> (or 0-length row.names)
: Warning messages:
: 1: In read.table(file = file, header = header, sep = sep, quote = quote,  :
:   invalid input found on input connection 'example_files/japanese_utf8.csv'
: 2: In read.table(file = file, header = header, sep = sep, quote = quote,  :
:   incomplete final line found by readTableHeader on 'example_files/japanese_utf8.csv'
: 

Ouch. OK, so how does it work?

* Encoding in R
Basically R gives you two (and only two!) ways of encoding strings. You can use the default encoding of your OS, or you can use UTF-8. On OS X and Linux these options are often the same, since the default OS encoding is usually UTF-8. On Windows there is no such luck. On my Windows 7 machine the default is "Windows codepage 1252". The problem with this is that many characters (such as Japanse) cannot be represented in codepage 1252. 
